version: '3.5'

services:
  db_server:
    image: mysql:5.7
    env_file:
        - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin
    env_file:
        - .env
    volumes:
      - /sessions
    ports:
      - "${PMA_WEB_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_server
    links:
      - db_server:db
    restart: always
    
  mysql-backup:
    build: ./dockerfiles/mysql-backup-s3
    env_file:
        - .env
    environment:
      MULTI_FILES: "yes"
      MYSQLDUMP_DATABASE: ${BACKUP_DATABASE}
      S3_PREFIX: ${S3_PREFIX}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: db_server
      MYSQL_USER: root
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT:  ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      SCHEDULE: "@daily"
    restart: always 
    depends_on:
      - db_server

